# Generated by Django 3.1.7 on 2021-09-16 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210916_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_title', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_desc', models.TextField(blank=True, null=True)),
                ('short_content', models.TextField(blank=True, null=True)),
                ('blog_image', models.ImageField(upload_to='static/images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Core',
        ),
    ]
